### ISSUE TITLE
Create ui for client

### ISSUE THREAD

**Issue by sidecuter** [sidecuter/InfinixCS-Qt#17]
Just create layout for client app

### TODO:
- [x] #28
- [x] #29

**Comment by mntcloud** [comment]
Can you describe in TODO list what we need in the UI

**Comment by sidecuter** [comment]
So, That's the plan.
- Two windows: login window (3 views) and main window (2 view)
- First of all make a login window, but if it will be hard to make several views for 1 window, create window for each of views
Login views: 
![login views](https://user-images.githubusercontent.com/31383841/229581556-8499fdb3-536f-404d-8dec-828bc0594b3b.png)
This views will change each other by clicking on action buttons, but we will do event binding later, now just ui

**Comment by sidecuter** [comment]
So, main window will have two views: first for choosing the task, and on second user will check his answer. This window represents student window. Window for teacher will be described later
After user will send answer to the task, and app will get response user will see Dialog window with "Success" or "Fail" message and button "OK"
Main window views:
![main_window](https://user-images.githubusercontent.com/31383841/229586219-3a17055d-d2ef-4cea-9a8f-4817c5518190.png)
